class Tokens(object):
    current_char:str
    def __init__(self, statement:str) -> None: ...
    def at_end(self) -> bool: ...
    def read_char(self) -> str: ...
    def read_until(self, seek:str) -> str: ...
        